typography_spectrum: 0.9527026108807266
content_rating:
  adult: false
color:
  lightness: 0.26913858456574014
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  saturation: 0.5576885533214796
  brandStrength: 0.5328715954590958
  rhythmicContrast: 0.07805532269521
github: true
opengraph:
  appId: taimour.zaman@facebook.com
layout_spectrum: 0.01788397227164985
analytics: {}
author:
  name: Taimour Zaman
  url: 'http://www.access-group.ca/'
  email: taimour@access-group.ca
name: The Access Group
navigation:
  - name: About Founder
    id: a2e776ca-dd0f-487c-a322-03c7ce9ba874
    type: content
  - name: Blog
    id: 19454a19-295d-48ce-9a89-55afc2089e27
    type: content
  - name: 'List of  Lead Generation Technologies, Consulting & Free Resources'
    id: f972a213-d9ff-4683-88e3-973556a1e66a
    type: content
  - name: Events & Webinars
    id: 6696f918-73f4-4997-b13e-7745525e31a9
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: >-
  Increase your sales using sales program and artificial intelligence
  technologies
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F7hraupLO3aA%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D7hraupLO3aA&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F7hraupLO3aA%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://youtu.be/7hraupLO3aA'
      keywords:
        - ''
      related: []
      author:
        - name: 'Taimour Zaman: The Access Group & OME'
          url: 'https://www.youtube.com/channel/UCsOMXjUN5sV9gbURIRGAfRg'
          avatar: {}
      '@context': 'http://schema.org'
      title: 056875168 4k mixed ethnicity business gr H264 420
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=7hraupLO3aA&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=7hraupLO3aA&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=7hraupLO3aA&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=7hraupLO3aA&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=7hraupLO3aA&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=7hraupLO3aA'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=7hraupLO3aA
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=7hraupLO3aA
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      description: 'Uploaded by Taimour Zaman: The Access Group & OME on 2017-06-26.'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
coverPrefs:
  filter: false
description: ''
purpose:
  - type: external
    url: 'https://live.vcita.com/site/taimourzaman'
    label: Book Your 3 Points Revenue Generation Blue Print
