name: The Access Group
analytics: {}
purpose:
  - type: external
    url: 'https://live.vcita.com/site/taimourzaman'
    label: Book Your 3 Points Revenue Generation Blue Print
github: true
author:
  name: Taimour Zaman
  url: 'http://www.access-group.ca/'
  email: taimour@access-group.ca
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
navigation:
  - name: Blog
    id: 19454a19-295d-48ce-9a89-55afc2089e27
    type: content
  - name: About Founder
    id: a2e776ca-dd0f-487c-a322-03c7ce9ba874
    type: content
  - name: 'List of  Lead Generation Technologies, Consulting & Free Resources'
    id: f972a213-d9ff-4683-88e3-973556a1e66a
    type: content
  - name: Events & Webinars
    id: 6696f918-73f4-4997-b13e-7745525e31a9
    type: content
layout_spectrum: 0.09726817852568508
color:
  lightness: 0.6439788252065456
  brandColors:
    - '#FFFFFF'
    - '#599EEF'
    - '#CFCFCF'
    - '#8CBBF5'
    - '#356FBA'
  saturation: 0.6331187585716385
  brandStrength: 0.004210160475795959
  rhythmicContrast: 0.3889499847617665
content_rating:
  adult: false
typography_spectrum: 0.9555676956204605
opengraph:
  appId: taimour.zaman@facebook.com
title: >-
  Increase your sales using sales program and artificial intelligence
  technologies
coverPrefs:
  filter: false
description: ''
